README.md
this is trivial for `on: push`, but might be helpful to remind readers that this ain't always so for other events.
Hence the link to the docs.
=> clarify default checkout sha

README.md
=> add docs about checking out the triggering ref

.github/workflows/test.yml, README.md, action.yml
https://github.com/github/dreamlifter/issues/1297
Checkout will persist the git credential into the repository git config file.
If the token has write-access to the repository, workflow user can use
```yaml
- run: |
git commit -am "changes"
git push
```
to push the change back to the repository without dealing with git authentication.
=> Upgrade checkout to v1.1.0 to better support scripting git.

.github/workflows/test.yml, CHANGELOG.md, README.md, action.yml
The updates were breaking user's builds #60, #62.
=> Reverted Changes to Git Config and Authentication

README.md
`github.event.after` fails when Pull Request has just been created. At that time, `after` or `before` commit sha's do not exist. They exist during PR `synchronize` action.
Whereas `github.event.pull_request.head.sha` will work for both PR `opened` action as well as PR `synchronize` action.
Ref: #61
=> Fix checkout head commit of PR

.github/workflows/test.yml, README.md, __test__/retry-helper.test.ts, __test__/verify-basic.sh, dist/index.js, package-lock.json, package.json, src/git-command-manager.ts, src/git-source-provider.ts, src/github-api-helper.ts, src/main.ts, src/retry-helper.ts, src/state-helper.ts
fixes https://github.com/actions/checkout/issues/97
=> fallback to REST API to download repo

README.md
=> improve summary

dist/index.js, src/git-command-manager.ts
=> fix issue checking detached when git less than 2.22

README.md, action.yml, src/misc/generate-docs.ts
=> Add link to doc for creating and using encrypted secrets

__test__/input-helper.test.ts, dist/index.js, src/input-helper.ts
=> fix ref for pr closed event when a pr is merged

README.md
This is just a documentation change, explaining how to fix submodules that are configured to use SSH URLs instead of HTTPS URLs. Spent a while banging my head on the wall and hope this saves someone else the pain.
This is helpful for teams that use the SSH protocol for local development so don't want to change the mechanism that pulls in the submodules.
=> Handle submodules with SSH URLs

adrs/0153-checkout-v2.md
Proposing adding SSH support. This will help for users scripting submodule checkout.
Will open a separate ADR for a first-class `submodule` input.
=> revise adr to support ssh

adrs/0153-checkout-v2.md
This change converts SSH URLs to HTTPS when an SSH key is not supplied.
Related to https://github.com/actions/checkout/issues/116#issuecomment-595472358
=> revise ADR: convert SSH URL to HTTPS

.github/workflows/test.yml, dist/index.js, src/git-auth-helper.ts
=> convert SSH URL to HTTPS

README.md, __test__/git-auth-helper.test.ts, action.yml, dist/index.js, src/git-auth-helper.ts, src/git-source-provider.ts, src/git-source-settings.ts, src/input-helper.ts, src/misc/generate-docs.ts, src/state-helper.ts
related to ADR https://github.com/actions/checkout/pull/156
=> add ssh support

dist/index.js, src/git-auth-helper.ts, src/git-source-provider.ts, src/github-api-helper.ts, src/url-helper.ts
For GHES alpha release, leverage GITHUB_URL to determine clone URL (may change post alpha)
=> changes to support ghes alpha release

dist/index.js, src/git-auth-helper.ts, src/git-directory-helper.ts, src/git-source-provider.ts, src/git-source-settings.ts
Collapse log output into logical groups for a nicer experience
=> group output

dist/index.js, package-lock.json, package.json, src/github-api-helper.ts, src/url-helper.ts
Let the toolkit set the baseUrl (GHES vs Dotcom) when constructing the Octokit REST client
=> consume new @actions/github for GHES support

package.json
Noticed that if you don't quote the glob pattern it doesn't reach past the first level.
After this change `src/misc/generate-docs.ts` will be included:
```diff
npm run format
>> checkout@2.0.2 format /Users/peter.evans/git/checkout
>> prettier --write '**/*.ts'
__test__/git-auth-helper.test.ts 303ms
__test__/git-directory-helper.test.ts 84ms
__test__/git-version.test.ts 23ms
__test__/input-helper.test.ts 22ms
__test__/ref-helper.test.ts 28ms
__test__/retry-helper.test.ts 12ms
src/fs-helper.ts 9ms
src/git-auth-helper.ts 64ms
src/git-command-manager.ts 79ms
src/git-directory-helper.ts 19ms
src/git-source-provider.ts 30ms
src/git-source-settings.ts 10ms
src/git-version.ts 17ms
src/github-api-helper.ts 22ms
src/input-helper.ts 27ms
src/main.ts 11ms
+src/misc/generate-docs.ts 23ms …
```
=> fix prettier glob pattern

dist/index.js, src/git-command-manager.ts, src/git-source-provider.ts, src/ref-helper.ts
Adding temporary telemetry because we're sometimes receiving the wrong merge commit. Adding telemetry here, since only place that already has enough info to detect (commit message).
=> telemetry for incorrect merge commit

README.md, __test__/git-auth-helper.test.ts, __test__/git-directory-helper.test.ts, adrs/0153-checkout-v2.md, dist/index.js, src/git-command-manager.ts, src/git-directory-helper.ts, src/git-source-provider.ts, src/ref-helper.ts
Fetch all history for all tags and branches when `fetch-depth: 0`
Fixes #240
Fixes #239
Fixes #214
Fixes #204
Fixes #93
Related #250
Related #217
=> Fetch all history for all tags and branches when fetch-depth=0

README.md, __test__/input-helper.test.ts, action.yml, dist/index.js, src/git-source-provider.ts, src/github-api-helper.ts, src/input-helper.ts
=> determine default branch

__test__/git-auth-helper.test.ts, __test__/git-directory-helper.test.ts, dist/index.js, src/git-command-manager.ts, src/git-source-provider.ts, src/github-api-helper.ts
Fixes https://github.com/actions/checkout/issues/283
=> fix default branch for .wiki and when using ssh

.eslintrc.json, dist/index.js, src/git-auth-helper.ts, src/github-api-helper.ts
In our testing, this fixes a flakiness we observed in the recursive checkout of submodules, where `remote.origin.url` is _sometimes_ not set after checkout.
/cc @igfoo
=> Add missing `await`s

__test__/git-auth-helper.test.ts, __test__/input-helper.test.ts, dist/index.js, src/git-auth-helper.ts, src/git-command-manager.ts, src/git-source-settings.ts, src/input-helper.ts, src/main.ts, src/workflow-context-helper.ts
fixes https://github.com/actions/checkout/issues/570
When [ssl certificate authentication](https://github.blog/2019-08-14-ssh-certificate-authentication-for-github-enterprise-cloud/) is enabled, the clone UI suggested in the UI is like `org-<ORG_ID>@github.com:<ORG>/<REPO>.git` instead of the normal format `git@github.com:<ORG>/<REPO>.git`
We need to register a git config `insteadOf` url to handle the new format. Today users set the input `submodules: true` and the input `ssh-key` is not provided, we register an insteadOf config so SSH URLs beginning with `git@github.com:` are converted to HTTPS. We need to do the same thing for the new format.
=> set insteadOf url for org-id

README.md
Github doesn't allow secret names that start with `GITHUB_` (case insensitive). Update README to choose a different prefix (GH).
=> Change secret name for PAT to not start with GITHUB_

CHANGELOG.md, __test__/git-auth-helper.test.ts, dist/index.js, src/git-auth-helper.ts, src/git-source-provider.ts
This pr fixes #760 by setting the repositories path as a safe directory when running checkout and removing that config on cleanup.
We aren't able to set it as a local config, as this setting only works for global configs.
So, using the standard we used for submodules, lets go ahead and copy the existing global config to a new location. Then we can go ahead and modify that global config (so we don't modify like a users global config if they test something on a self hosted runner real fast). Then, we can delete that global config at the end of the checkout step.
This does carry some limitations, it doesn't persist this configuration for the duration of the job mainly. So if your job pushes to git or something after checkout, that will continue to fail. We need to figure out how to address …
=> Enforce safe directory

.github/workflows/test.yml, README.md, __test__/git-auth-helper.test.ts, __test__/input-helper.test.ts, action.yml, dist/index.js, src/git-auth-helper.ts, src/git-source-provider.ts, src/git-source-settings.ts, src/input-helper.ts, src/state-helper.ts
* Add set-safe-directory input to allow customers to take control.
=> Add set-safe-directory input to allow customers to take control. (#770)

.github/workflows/update-main-version.yml
This adds a new workflow to help moving a main version tag (e.g. `v3) to a new reference
=> Add workflow to update a main version

.github/workflows/test.yml, CONTRIBUTING.md
Our CI relied on `datadog/squid` Docker image which has now been deleted.
I noticed we also don't have a contributing doc which explains to new contributors how to update the JS bundle. I've copied the relevant section from [actions/labeler](https://github.com/actions/labeler/blob/main/CONTRIBUTING.md) to get one started.
=> Replace datadog/squid with ubuntu/squid Docker image

.licenses/npm/qs.dep.yml, __test__/git-command-manager.test.ts, dist/index.js, package-lock.json, src/git-command-manager.ts
When trying to list local branches to figure out what needs cleaned up during runs on non-ephemeral Actions Runners, we use `git rev-parse --symbolic-full-name` to get a list of branches. This can lead to ambiguous ref name errors when there are branches and tags with similar names. 
Part of the reason we use `rev-parse --symbolic-full-name` vs `git branch --list` or `git rev-parse --symbolic` seems to related to a bug in Git 2.18. Until we can deprecate our usage of Git 2.18, I think we need to keep `--symbolic-full-name`. Since part of the problem is that these ambiguous ref name errors clog the Actions annotation limits, this is a mitigation to suppress those messages until we can get rid of the workaround.
See https://github.com/actions/checkout/issues/786
=> Implement branch list using callbacks from exec function

README.md
Updated the README to link to the private repo checkout and be explicit about it.
Fixes #1021
=> Add in explicit reference to private checkout options

dist/index.js, src/git-auth-helper.ts
Rotate public RSA key for ssh interaction with github.com - see https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
=> Add new public key for known_hosts

dist/index.js, src/github-api-helper.ts, src/ref-helper.ts
Using the new version of the github package no longer implicitly translates [api.github.com](http://api.github.com/) into the GHES equvivalent.
This PR fixes the bug introduced in #1246
=> Fix: convert baseUrl to serverApiUrl 'formatted'

adrs/0153-checkout-v2.md, dist/index.js, src/git-directory-helper.ts
Includes a change in an ADR (`0153-checkout-v2.md`). I can revert that change if you would rather not modify ADRs.
=> Fix typos found by codespell

README.md, __test__/git-auth-helper.test.ts, __test__/git-command-manager.test.ts, __test__/input-helper.test.ts, action.yml, dist/index.js, src/git-command-manager.ts, src/git-source-provider.ts, src/git-source-settings.ts, src/input-helper.ts
Hi there!
This PR adds an optional `fetch-tags` option that can be used to override the default behavior of adding the `--no-tags` arg to the generated `git fetch` command if `fetch-depth` is configured and not `0`.
This way, users can use fetch-depth while still getting the tags inside this range, which can e.g.  be important when using automatic GIT versioning plugins like [jgitver](https://github.com/jgitver/jgitver).
Tested using a workflow on a separate branch that verifies function as well as backwards compatibility: See [Run 5432963197](https://github.com/RobertWieczoreck/checkout/actions/runs/5432963197/jobs/9880354020).
All Checks are green.
Also see [PR 2](https://github.com/RobertWieczoreck/checkout/pull/2) in my fork (description is mostly copied from there).
Fixes #448 …
=> Add option to fetch tags even if fetch-depth > 0

README.md, __test__/git-auth-helper.test.ts, __test__/git-command-manager.test.ts, __test__/input-helper.test.ts, action.yml, dist/index.js, src/git-command-manager.ts, src/git-source-provider.ts, src/git-source-settings.ts, src/input-helper.ts
If this is merged, setting the `progress` option to false in the `with` section of the workflow step will cause git fetch to run without the `--progress` flag.
Note that the default value of this new option is `true`, which matches the current behavior, so this PR introduces no behavior change unless the new option is explicitly present and set to false.
The motivation is to be able to suppress the noisy progress status output which adds many hundreds of `remote: Counting objects: 85% (386/453)` and similar lines in the workflow log.
This should be sufficient to resolve #894 and its older friends, though the solution is different to the one proposed there because it doesn't use the `--quiet` flag. IIUC git doesn't show the progress status by default when running on GitHub since the output …
=> Support fetching without the --progress option

README.md
No hardcoded language in the URL and uses the correct docs.github.com domain.
=> Correct link to GitHub Docs

images/test-ubuntu-git.Dockerfile, images/test-ubuntu-git.md
By default, `test-ubuntu-git` is inheriting the `README.md` of `actions/checkout`.
It should have a separate README.  This PR achieves that.
=> Give `test-ubuntu-git` its own `README`

.github/workflows/update-test-ubuntu-git.yml
When we built the `test-ubuntu-git` image generation workflow, we made the decision to only allow the `test-ubuntu-git` container image to be published from the `main` branch of `actions/checkout`.  (see https://github.com/actions/checkout/pull/1617)
This PR updates the workflow to explain (via a warning message) why an image push attempt from a non-`main` branch didn't have the desired effect (for users that weren't paying close attention to the label of the checkbox which reads:  `"Publish to ghcr.io? (main branch only)"`).
Note that `push` is an opt-in behavior of reusable workflow `docker/build-push-action`. 
There's diagnostic value in the build attempt that precedes any would-be image push, so I chose not to fail the workflow outright, but rather to let the build proceed and simply …
=> Warn on attempts to publish `test-ubuntu-git` from non-main branch.

CHANGELOG.md, package-lock.json, package.json
- Add v4.1.2 and v4.1.1 to CHANGELOG.md
- Bump version in `package.json` to 4.1.2
- Ran `npm i` to regenerate `package-lock.json`
=> Prep for release of  v4.1.2 

__test__/git-auth-helper.test.ts, __test__/git-directory-helper.test.ts, __test__/git-version.test.ts, dist/index.js, package-lock.json, package.json, src/git-command-manager.ts, src/git-source-provider.ts
This is a fix for a [bug](https://github.com/actions/checkout/issues/1651) discovered when we attempted to release v4.1.2.
Some self-hosted runners have older git versions that pre-date git's `sparse-checkout` command.
=> Check git version before attempting to disable `sparse-checkout`

README.md, __test__/git-auth-helper.test.ts, action.yml, dist/index.js, src/git-source-settings.ts, src/input-helper.ts, src/url-helper.ts
https://github.com/github/actions-launch/issues/427
=> Add SSH user parameter

.github/workflows/test.yml, __test__/verify-basic.sh, dist/index.js, src/git-command-manager.ts
When we released v4.1.3, there were reports that it interfered with some third party tools.
see the following issues:
- https://github.com/actions/checkout/issues/1689
- https://github.com/actions/checkout/issues/1690
- https://github.com/actions/checkout/issues/1691
It turns out that calling `git sparse-checkout disable` has a side effect.  It places the local repo clone in [worktree mode](https://git-scm.com/docs/git-worktree), albeit with only a single "tree".
This fix neutralizes that side effect by explicitly disabling worktree mode.
=> Disable `extensions.worktreeConfig` when disabling `sparse-checkout`

dist/index.js, src/github-api-helper.ts
After updating the NPM dependencies, archive based checkouts were broken on Windows machines that do not have Git.exe in a location that `actions/checkout` understands.
This is because `@actions/tool-cache` was updated with a Powershell command `Expand-Archive`. This command explicitly checks the file name includes the `.zip` extension a the end. For whatever reason, `actions/checkout` was writing the extension as `.gz` regardless of the compression format used.
Before:
After:
---
https://github.com/actions/checkout/issues/1721
=> Check platform to set archive extension appropriately

__test__/ref-helper.test.ts, dist/index.js, src/ref-helper.ts
The code that chooses what ref to check out assumes that if something is not a branch or a pull request it must be a tag, but that is not necessarily true. When the ref is not a pull request, branch or tag, we should instead check out the commit directly.
=> Check out other refs/* by commit

.github/workflows/check-dist.yml, .github/workflows/codeql-analysis.yml, .github/workflows/licensed.yml, .github/workflows/test.yml, .github/workflows/update-main-version.yml
Dependabot tried to update our internal CI workflows to the bleeding edge.  
It's safer to pin these to a specific version in order to minimize the chances of us having to jump through extra mitigation hoops in the event of a bad release.
In a roll-forward scenario, it's conceivable that a bad release could block the CI of any release candidate intended to replace it.  (It could even potentially block the `update-main-version` workflow -- a *real* chicken-and-egg problem!)  Under those circumstances, we'd have to roll-back to an older version just to get all the necessary workflows passing before we could roll forward.
=> Pin actions/checkout's own workflows to a known, good, stable version.

README.md
When reading the doc it wasn't clear where the email numerical prefix came from. A short `NOTE` would be helpful.
=> Provide explanation for where user email came from

.github/workflows/test.yml, action.yml, dist/index.js, src/git-source-provider.ts, src/main.ts
Adds outputs for `ref` and `commit`.
Closes #281
=> Add Ref and Commit outputs

__test__/ref-helper.test.ts, dist/index.js, src/ref-helper.ts
This should resolve https://github.com/actions/checkout/issues/1782
=> Check out other refs/* by commit if provided, fall back to ref

__test__/url-helper.test.ts
`isGhes` is an exported function that was lacking unit test coverage.  This PR adds unit tests for `isGhes`.
=> Expand unit test coverage for `isGhes`

README.md
This pull request includes minor updates to the `README.md` file to clarify instructions for checking out multiple repositories. The changes specify that the instructions apply to both private and internal repositories.
=> Add internal repos for checking out multiple repositories

README.md
This pull request updates the documentation to highlight the new default support for Node.js 24 in Checkout v5 and clarifies the minimum Actions Runner version required. This was previously only mentioned in the runner release notes.
To help with https://github.com/actions/checkout/issues/2240
=> Update README to include Node.js 24 support details and requirements
