- action.yml
* Only specify `-f` (force) once.
* Submodule documentation improvements
> Some documentation cleanups

- README.md
version is deprecated and replaced by node-version
> (docs) Change version to node-version

- README.md
I guess this action doesn't technically make sure that my working directory is `$GITHUB_WORKSPACE`, so this might be more precise?
> clarify language on working directory

- action.yml
@thboop to review. Once this is in we should do the same in upload/download artifact
> Add explanatory comment to plugin

- action.yml
Explain that submodules have several settings: `false`, `true` or `recursive`.
> Explain submodules option

- README.md
We extracted the secrets section out of the currently linked article. This is the most up-to-date and might solve some reports on [Twitter](https://twitter.com/quinnypig/status/1193623882835492864?s=12).
> Update help docs link

- dist/index.js
- src/git-source-provider.ts
> Do not delete cwd

- README.md
- action.yml
> clarify name with owner

- README.md
> document scenario: checkout the head commit of a PR

- README.md
fixes #100 
fixes #99 
fixes #91 
fixes #81 
fixes #61 
fixes #45
> add more scenarios

- README.md
https://github.com/actions/checkout/issues/176
https://github.com/actions/checkout/issues/116
> Updated documentation based on new changes

- __test__/verify-no-unstaged-changes.sh
fixes https://github.com/actions/checkout/issues/263.
> build because all is no more

- README.md
- action.yml
> improve description for fetch-depth

- __test__/override-git-version.cmd
- __test__/override-git-version.sh
The newest toolkit version uses [Environment files](https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files) to communicate with the Runner. This pr moves towards the new way of communicating with the runner and updates the toolkit version if appropriate.
> Swap to Environment Files

- README.md
Current linked content doesn't render, proposing changing to this status badge.
> README - fix status badge

- CHANGELOG.md
- package-lock.json
- package.json
Sync checkout version with tag version.
Will slide tag as soon as merged
> Release v3.5.1

- README.md
- src/misc/generate-docs.ts
> Update README.md for V4

- README.md
[Rendered](https://github.com/actions/checkout/blob/e7e449dced768f0201582e76e92398df44e85f4f/README.md)
https://github.com/actions/checkout/issues/1497
> Link to release page from what's new section

- CHANGELOG.md
- package-lock.json
- package.json
Update versioning artifacts in preparation for release v4.1.4
> Prep Release v4.1.4

- CHANGELOG.md
- package-lock.json
- package.json
This release includes the changes from #1739, #1697, #1774, and #1776
> Prepare 4.1.7 release

- CHANGELOG.md
- package-lock.json
- package.json
This release includes the changes from #1180, #1777, and #1872
> Prepare 4.2.0 release

- CHANGELOG.md
- package-lock.json
- package.json
This release includes the changes from #1924 to resolve #1782
> Prepare 4.2.1 release

- README.md
Add new Recommended permissions section to the README file.
> Documentation update - add recommended permissions to Readme

- CHANGELOG.md
- package-lock.json
- package.json
Release v4.3.0 includes updates to the README, adjustments to documentation, and dependency updates. It also introduces internal repositories for checking out multiple repositories.
> Prepare release v4.3.0
